/**
 * Comments Hooks
 *
 * Generated using the Redux factory - only 20 lines of code!
 */

import { createCrudHooks } from '@/lib/redux-factory';
import { commentsSlice } from '../redux';
import type { Comment } from '../types';

/**
 * Complete CRUD hooks with pagination
 * Generated by createCrudHooks factory
 */
export const {
  useList: useComments,
  useEntity: useComment,
} = createCrudHooks<Comment>({
  slice: commentsSlice,
  sliceName: 'comments',
});
