/**
 * Comments Hooks
 *
 * Generated using the Redux factory - only 20 lines of code!
 */

import { createCrudHooks } from '@/lib/redux-factory';
import { commentsSlice } from '../redux';

/**
 * Complete CRUD hooks with pagination, search, and selection
 * Generated by createCrudHooks factory
 */
export const {
  useList: useComments,
  useEntity: useComment,
  useSelection: useCommentSelection,
} = createCrudHooks<Comment, CreateCommentInput, UpdateCommentInput>({
  slice: commentsSlice,
  sliceName: 'comments',
});

// Import types for reference
import type { Comment, CreateCommentInput, UpdateCommentInput } from '../types';
