/**
 * Comments Redux Slice
 *
 * Generated using the Redux factory - only 20 lines of code!
 */

import { createCrudSlice } from '@/lib/redux-factory';
import { commentsApi } from '../services/comments';
import type { Comment, CreateCommentInput, UpdateCommentInput } from '../types';

/**
 * Complete Redux slice with CRUD operations, pagination, and caching
 * Generated by createCrudSlice factory
 */
export const commentsSlice = createCrudSlice<Comment, CreateCommentInput, UpdateCommentInput>({
  name: 'comments',
  apiService: commentsApi,
  enableCache: true,
  enableOptimisticUpdates: true,
});

// Export reducer for store configuration
export const { reducer } = commentsSlice;

// Export types for use in components
export type { CrudState as CommentsState } from '@/lib/redux-factory/types';
