/**
 * Comments Redux Slice
 *
 * Using simplified Redux factory
 */

import { createCrudSlice } from '@/lib/redux-factory';
import type { Comment, CreateCommentInput, UpdateCommentInput } from '../types';

/**
 * Complete Redux slice with CRUD operations
 * Generated by simplified createCrudSlice factory
 */
export const commentsSlice = createCrudSlice<Comment>({
  name: 'comments',
  endpoint: '/comments',
});

// Export reducer for store configuration
export const { reducer } = commentsSlice;

// Export actions for direct dispatch if needed
export const { actions } = commentsSlice;

// Export thunks for direct dispatch if needed
export const { thunks } = commentsSlice;

// Export types
export type { CrudState as CommentsState } from '@/lib/redux-factory/types';
